/** Machine-readable API error codes — mirror backend ERROR_CODE. */
export const ERROR_CODE = {
  // Validation
  VALIDATION_FAILED: "VALIDATION_FAILED",

  // Auth
  USERNAME_EXISTS: "USERNAME_EXISTS",
  EMAIL_ALREADY_USED: "EMAIL_ALREADY_USED",
  EMAIL_REQUIRED: "EMAIL_REQUIRED",
  EMAIL_INVALID: "EMAIL_INVALID",
  PASSWORD_REQUIRED: "PASSWORD_REQUIRED",
  PASSWORD_TOO_SHORT: "PASSWORD_TOO_SHORT",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  ACCOUNT_DEACTIVATED: "ACCOUNT_DEACTIVATED",
  TOKEN_INVALID: "TOKEN_INVALID",
  ACCESS_DENIED: "ACCESS_DENIED",
  FORBIDDEN_OPERATION: "FORBIDDEN_OPERATION",

  // User
  USER_NOT_FOUND: "USER_NOT_FOUND",
  CANNOT_CHANGE_PASSWORD: "CANNOT_CHANGE_PASSWORD",
  CURRENT_PASSWORD_WRONG: "CURRENT_PASSWORD_WRONG",

  // Common IDs
  USER_ID_REQUIRED: "USER_ID_REQUIRED",
  WRITING_ID_REQUIRED: "WRITING_ID_REQUIRED",
  ANALYTICS_ID_REQUIRED: "ANALYTICS_ID_REQUIRED",
  WRITING_IDS_REQUIRED: "WRITING_IDS_REQUIRED",

  // Writing
  WRITING_NOT_FOUND: "WRITING_NOT_FOUND",
  WRITING_ACCESS_DENIED: "WRITING_ACCESS_DENIED",
  WRITING_TYPE_NOT_SUPPORTED: "WRITING_TYPE_NOT_SUPPORTED",
  OUTLINE_GENERATION_FAILED: "OUTLINE_GENERATION_FAILED",
  PROMPT_GENERATION_FAILED: "PROMPT_GENERATION_FAILED",

  // Analytics / AI
  ANALYTICS_NOT_FOUND: "ANALYTICS_NOT_FOUND",
  ANALYTICS_ACCESS_DENIED: "ANALYTICS_ACCESS_DENIED",
  ANALYTICS_EXPORT_NO_DATA: "ANALYTICS_EXPORT_NO_DATA",
  TOKEN_LIMIT_EXCEEDED: "TOKEN_LIMIT_EXCEEDED",
  AI_ANALYSIS_FAILED: "AI_ANALYSIS_FAILED",
  AI_INVALID_RESPONSE: "AI_INVALID_RESPONSE",

  // Revision
  REVISION_NOT_FOUND: "REVISION_NOT_FOUND",

  // Suggestions
  SUGGESTION_NOT_FOUND: "SUGGESTION_NOT_FOUND",
  ANALYSIS_NOT_FOUND: "ANALYSIS_NOT_FOUND",
  NO_SUGGESTIONS_IN_REPORT: "NO_SUGGESTIONS_IN_REPORT",

  // Share
  WRITING_NOT_PUBLIC: "WRITING_NOT_PUBLIC",
  RELATED_WRITING_NOT_FOUND: "RELATED_WRITING_NOT_FOUND",

  // Documents
  FILE_REQUIRED: "FILE_REQUIRED",
  FILE_TOO_LARGE: "FILE_TOO_LARGE",
  DOC_LEGACY_NOT_SUPPORTED: "DOC_LEGACY_NOT_SUPPORTED",
  FILE_TYPE_DOCX_ONLY: "FILE_TYPE_DOCX_ONLY",
  FILE_INVALID_MIME: "FILE_INVALID_MIME",
  FILE_EMPTY_OR_CORRUPT: "FILE_EMPTY_OR_CORRUPT",

  // Books
  BOOK_NOT_FOUND: "BOOK_NOT_FOUND",
  BOOK_RECOMMENDATION_FAILED: "BOOK_RECOMMENDATION_FAILED",
  BOOK_CATALOG_EMPTY: "BOOK_CATALOG_EMPTY",

  CHAPTER_NOT_FOUND: "CHAPTER_NOT_FOUND",
  BOOK_NO_CHAPTERS: "BOOK_NO_CHAPTERS",
  BOOK_INGEST_FAILED: "BOOK_INGEST_FAILED",
  UNSUPPORTED_BOOK_FORMAT: "UNSUPPORTED_BOOK_FORMAT",
  BOOK_FILE_TOO_LARGE: "BOOK_FILE_TOO_LARGE",

  // Export
  EXPORT_ACCESS_DENIED: "EXPORT_ACCESS_DENIED",

  // AI provider
  AI_SUGGESTION_GENERATION_FAILED: "AI_SUGGESTION_GENERATION_FAILED",
  GEMINI_EMPTY_RESPONSE: "GEMINI_EMPTY_RESPONSE",
  GEMINI_RATE_LIMITED: "GEMINI_RATE_LIMITED",
  GEMINI_MODEL_NOT_FOUND: "GEMINI_MODEL_NOT_FOUND",
  GEMINI_API_KEY_INVALID: "GEMINI_API_KEY_INVALID",
  GEMINI_SERVICE_UNAVAILABLE: "GEMINI_SERVICE_UNAVAILABLE",
  TOKEN_LIMIT_CHECK_FAILED: "TOKEN_LIMIT_CHECK_FAILED",
} as const;

export type ErrorCode = (typeof ERROR_CODE)[keyof typeof ERROR_CODE];
